// Generated by CoffeeScript 1.6.3
var HandanParser, IRToy, NecParser;

NecParser = require('./lib/NecParser');

HandanParser = require('./lib/HandanParser');

IRToy = require('./lib/IRToy');

module.exports = {
  IRToy: IRToy,
  NecParser: NecParser,
  HandanParser: HandanParser
};
