// Generated by CoffeeScript 1.6.3
var HandanParser, IRToy, NecParser, handan, nec, toy;

IRToy = require('../js/index.js').IRToy;

NecParser = require('../js/index.js').NecParser;

HandanParser = require('../js/index.js').HandanParser;

toy = new IRToy('/dev/ttyACM0');

nec = new NecParser();

handan = new HandanParser();

toy.registerParser(nec);

toy.registerParser(handan);

toy.on('ircodereceived', function(ir_code) {
  console.log("Code received from IR remote", ir_code);
  return toy.transmit({
    address: 8403,
    code: 224,
    type: 'handan'
  });
});
